image: node:10

pipelines:
  pull-requests:
    '**':
      - step:
          caches:
            - nodecustom
            - yarn
          script:
            - export export TZ='Asia/Jakarta'
            - yarn
            - yarn test

definitions:
  caches:
    nodecustom: ./node_modules
    yarn: /usr/local/share/.cache/yarn
